#############################################################################
# Makefile for building: QtCyCells
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Jun 28 15:54:49 2013
# Project:  QtCyCells.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile QtCyCells.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I. -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lglut -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = action.cpp \
		cells.cpp \
		cellType.cpp \
		dataDialog.cpp \
		fileDef.cpp \
		fileInit.cpp \
		history.cpp \
		historyView.cpp \
		main.cpp \
		molecule.cpp \
		QtCyCells.cpp \
		QtEngineThread.cpp \
		random.cpp \
		sense.cpp \
		simView.cpp \
		simView3D.cpp \
		simMolView3D.cpp \
		tallyActions.cpp \
		tissue.cpp moc_dataDialog.cpp \
		moc_QtCyCells.cpp \
		moc_QtEngineThread.cpp \
		moc_simView.cpp
OBJECTS       = action.o \
		cells.o \
		cellType.o \
		dataDialog.o \
		fileDef.o \
		fileInit.o \
		history.o \
		historyView.o \
		main.o \
		molecule.o \
		QtCyCells.o \
		QtEngineThread.o \
		random.o \
		sense.o \
		simView.o \
		simView3D.o \
		simMolView3D.o \
		tallyActions.o \
		tissue.o \
		moc_dataDialog.o \
		moc_QtCyCells.o \
		moc_QtEngineThread.o \
		moc_simView.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QtCyCells.pro
QMAKE_TARGET  = QtCyCells
DESTDIR       = 
TARGET        = QtCyCells

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_DataDialog.h ui_QtCyCells.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtCyCells.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile QtCyCells.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile QtCyCells.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QtCyCells1.0.0 || $(MKDIR) .tmp/QtCyCells1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QtCyCells1.0.0/ && $(COPY_FILE) --parents action.h array3D.h cell.h cells.h cellType.h color.h condition.h dataDialog.h fileDef.h fileInit.h history.h historyView.h molecule.h process.h QtCyCells.h QtEngineThread.h random.h rate.h sense.h simPoint.h simView.h simView3D.h simMolView3D.h tallyActions.h tissue.h util.h .tmp/QtCyCells1.0.0/ && $(COPY_FILE) --parents action.cpp cells.cpp cellType.cpp dataDialog.cpp fileDef.cpp fileInit.cpp history.cpp historyView.cpp main.cpp molecule.cpp QtCyCells.cpp QtEngineThread.cpp random.cpp sense.cpp simView.cpp simView3D.cpp simMolView3D.cpp tallyActions.cpp tissue.cpp .tmp/QtCyCells1.0.0/ && $(COPY_FILE) --parents DataDialog.ui QtCyCells.ui .tmp/QtCyCells1.0.0/ && (cd `dirname .tmp/QtCyCells1.0.0` && $(TAR) QtCyCells1.0.0.tar QtCyCells1.0.0 && $(COMPRESS) QtCyCells1.0.0.tar) && $(MOVE) `dirname .tmp/QtCyCells1.0.0`/QtCyCells1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtCyCells1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dataDialog.cpp moc_QtCyCells.cpp moc_QtEngineThread.cpp moc_simView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dataDialog.cpp moc_QtCyCells.cpp moc_QtEngineThread.cpp moc_simView.cpp
moc_dataDialog.cpp: ui_DataDialog.h \
		dataDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dataDialog.h -o moc_dataDialog.cpp

moc_QtCyCells.cpp: QtEngineThread.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		ui_QtCyCells.h \
		QtCyCells.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) QtCyCells.h -o moc_QtCyCells.cpp

moc_QtEngineThread.cpp: tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		QtEngineThread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) QtEngineThread.h -o moc_QtEngineThread.cpp

moc_simView.cpp: color.h \
		simView.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) simView.h -o moc_simView.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_DataDialog.h ui_QtCyCells.h
compiler_uic_clean:
	-$(DEL_FILE) ui_DataDialog.h ui_QtCyCells.h
ui_DataDialog.h: DataDialog.ui
	/usr/bin/uic-qt4 DataDialog.ui -o ui_DataDialog.h

ui_QtCyCells.h: QtCyCells.ui
	/usr/bin/uic-qt4 QtCyCells.ui -o ui_QtCyCells.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

action.o: action.cpp action.h \
		cellType.h \
		cell.h \
		simPoint.h \
		cells.h \
		array3D.h \
		molecule.h \
		random.h \
		tallyActions.h \
		rate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o action.o action.cpp

cells.o: cells.cpp cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		random.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cells.o cells.cpp

cellType.o: cellType.cpp cellType.h \
		cell.h \
		simPoint.h \
		sense.h \
		process.h \
		rate.h \
		condition.h \
		random.h \
		util.h \
		tallyActions.h \
		action.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cellType.o cellType.cpp

dataDialog.o: dataDialog.cpp dataDialog.h \
		ui_DataDialog.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		history.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataDialog.o dataDialog.cpp

fileDef.o: fileDef.cpp fileDef.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		sense.h \
		rate.h \
		condition.h \
		random.h \
		action.h \
		process.h \
		util.h \
		tallyActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileDef.o fileDef.cpp

fileInit.o: fileInit.cpp fileInit.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		random.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileInit.o fileInit.cpp

history.o: history.cpp history.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o history.o history.cpp

historyView.o: historyView.cpp historyView.h \
		simView.h \
		color.h \
		history.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historyView.o historyView.cpp

main.o: main.cpp QtCyCells.h \
		QtEngineThread.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		ui_QtCyCells.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

molecule.o: molecule.cpp molecule.h \
		array3D.h \
		simPoint.h \
		random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o molecule.o molecule.cpp

QtCyCells.o: QtCyCells.cpp QtCyCells.h \
		QtEngineThread.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		ui_QtCyCells.h \
		history.h \
		fileDef.h \
		fileInit.h \
		dataDialog.h \
		ui_DataDialog.h \
		simView3D.h \
		simView.h \
		color.h \
		historyView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtCyCells.o QtCyCells.cpp

QtEngineThread.o: QtEngineThread.cpp QtEngineThread.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		history.h \
		fileDef.h \
		fileInit.h \
		dataDialog.h \
		ui_DataDialog.h \
		simView.h \
		color.h \
		simView3D.h \
		simMolView3D.h \
		historyView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QtEngineThread.o QtEngineThread.cpp

random.o: random.cpp random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o random.o random.cpp

sense.o: sense.cpp sense.h \
		cell.h \
		simPoint.h \
		cells.h \
		array3D.h \
		molecule.h \
		random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sense.o sense.cpp

simView.o: simView.cpp simView.h \
		color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simView.o simView.cpp

simView3D.o: simView3D.cpp simView3D.h \
		simView.h \
		color.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simView3D.o simView3D.cpp

simMolView3D.o: simMolView3D.cpp simMolView3D.h \
		simView.h \
		color.h \
		tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simMolView3D.o simMolView3D.cpp

tallyActions.o: tallyActions.cpp tallyActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tallyActions.o tallyActions.cpp

tissue.o: tissue.cpp tissue.h \
		cells.h \
		cell.h \
		simPoint.h \
		array3D.h \
		cellType.h \
		molecule.h \
		random.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tissue.o tissue.cpp

moc_dataDialog.o: moc_dataDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataDialog.o moc_dataDialog.cpp

moc_QtCyCells.o: moc_QtCyCells.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtCyCells.o moc_QtCyCells.cpp

moc_QtEngineThread.o: moc_QtEngineThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QtEngineThread.o moc_QtEngineThread.cpp

moc_simView.o: moc_simView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simView.o moc_simView.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

